### ISSUE TITLE
tests are failing…

### ISSUE THREAD

**Issue by Sylvain303** [macie/unittest.sh#4]
It fails passing its own unittest.

xubuntu 14.10 
bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

How to reproduce:

git clone https://github.com/macie/unittest.sh.git
cd unittest.sh

out of the box using bash…

```
./unittest.sh 
./unittest.sh: 572: local: test_pattern}"): bad variable name
```

launched via bash

```
bash unittest.sh 
unittest.sh: line 580: test_some_func: command not found
./tmp/unittest.sh/tests/test_parsers.sh: line 35: ut_parser__parser: command not found
F/tmp/unittest.sh/tests/test_parsers.sh: line 45: ut_parser__parser: command not found
F/tmp/unittest.sh/tests/test_parsers.sh: line 56: ut_parser__parser: command not found
Funittest.sh: line 580: test_pattern="s/: No such file or directory
.unittest.sh: line 580: test_pattern}"): command not found
./tmp/unittest.sh/tests/test_parsers.sh: line 71: ut_parser__find_source_files: command not found
F/tmp/unittest.sh/tests/test_parsers.sh: line 86: ut_parser__find_functions: command not found
Funittest.sh: line 580: test_some_func': command not found
.....................................................................................................
```

**Comment by macie** [comment]
Hi. To tell the truth, I suspend this project, because of nearly unrealistic assumptions - full support for posix shell.
But if you found it, it means, there is a need for such tool. So I do my best to finish it.
Thanks :)

**Comment by Sylvain303** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Maciej,

On 20/01/2015 20:28, Maciej Żok wrote:
>
> Hi. To tell the truth, I suspend this project, because of nearly
unrealistic assumptions - full support for posix shell.
> But if you found it, it means, there is a need for such tool. So I do
my best to finish it.
> Thanks :)
>

There's also : http://testanything.org/producers.html

I don't know if it's still maintained.

I don't know if it needs to be POSIX compliant, I just wanna to test
some legacy code, an maintain test in many language, including shell
scripts, which may perform well on functional external testing…

Regards.

- -- 
Sylvain Viart - Consultant informatique système linux
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJUwQLOAAoJEAAaOVGJVmkjH/EP/2LDNN/K+1/I3bwl1CDthH6I
Zq7O0h3TKECeZd2Ii8IythA96yS58Db2oPi5WBsaqyJD6d6gBYAiY5AU9SrSL9RC
t+CzEHwpE1tPtkfpcalJGlzGrOlBLPDKwbtZyqvZl9b34uoBQAK04caLTRsU4bDH
ubvroGSvwxF3tTRAegnGrsD7/jJx9onQVu8z61bylMFEfTUiXFRvttV9sHj0EiEg
eetLYsfBzYPgOjvjb8s7Zu/oKCf28eKUNTW3M0QI72/56OYtc0OAG9lQ+YTo+HGl
3yFTZ2vGuZUOCyMX08GE2hYFpK/6BIcxAK4p5/ETpcesIKYVXDOJW6EwXH08/+GP
Euh/fPaWJuA/nSKrMiYsbJYtgagIA2AlzSVHA5bIE5EzI2msamO2Siqz/0pB+wdU
rhjQ6FvhHusbHE1Ka04YrXD1piVXtDLw5PquIPpZFQDLvLh5vKBmPxL3TrFJp+Wk
HJ+PoaMt+qf1ZSoGWb8CWngeU4bPh8JExnWANITeIci7jcSRd7swRJHpHtysN1C8
aQPRM39cKEKPweVgKbwGt+sg3+JJJpznlErIStilulkLTqOju8wVlOGjRgjiId0f
Vx4EfFnvSxvaEGyjaHQ9Vl6DeXrUfJ6TjchAgy2aaJBsOFW6QdGO5SRqafuCg/Sw
bd3BTK3Agesu29yyl3cV
=YfFu
-----END PGP SIGNATURE-----
